// REAL speaker diarization and speaker-aware transcription: real sherpa-onnx models, real
// whisper.cpp, real FFmpeg. Audio is SYNTHETIC (two macOS text-to-speech voices, generated by
// scripts/make-synthetic-conversations.py); no patient recordings are used anywhere.
// These are skipped (not passed) when the diarization environment is not installed:
// run `npm run setup:diarization`.
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { copyFileSync, mkdirSync, readFileSync } from "node:fs";
import path from "node:path";
import { afterEach, describe, test } from "node:test";
import {
  fixtureSynthetic, leftoverFiles, makeAuth, makeConfig, makeSilentWav, postAudio, readFixture, startServer, TEST_SUPABASE_URL,
} from "./helpers.js";
import { diarizationSetup, diarizeWav } from "../services/diarization.js";
import { checkReadiness } from "../services/readiness.js";

const cleanups = [];
afterEach(async () => {
  while (cleanups.length) await cleanups.pop()();
});

const truthOf = (name) => JSON.parse(readFileSync(fixtureSynthetic(`${name}.truth.json`), "utf8")).turns;

/** For each true turn, the diarized speaker id that covers most of it. */
function speakerPerTurn(turns, intervals) {
  return turns.map((turn) => {
    const cover = new Map();
    for (const interval of intervals) {
      const overlap = Math.min(turn.endMs, interval.endMs) - Math.max(turn.startMs, interval.startMs);
      if (overlap > 0) cover.set(interval.speaker, (cover.get(interval.speaker) ?? 0) + overlap);
    }
    return [...cover.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? null;
  });
}

async function realEnv() {
  const env = await makeConfig();
  cleanups.push(env.cleanup);
  const setup = await diarizationSetup(env.config);
  const installed = setup.python && setup.script && setup.models;
  const whisper = await checkReadiness(env.config);
  return { ...env, installed, whisperReady: whisper.ready };
}

describe("real diarization on synthetic conversations", () => {
  test("two speakers A->B->A->B: every turn correct with consistent ids, including one-word replies", async (t) => {
    const env = await realEnv();
    if (!env.installed) return t.skip("diarization not installed: npm run setup:diarization");
    const started = Date.now();
    const result = await diarizeWav(fixtureSynthetic("two-speaker.wav"), env.config, { timeoutMs: 60_000 });
    t.diagnostic(`diarized 17 s of audio in ${Date.now() - started} ms`);
    assert.equal(result.status, "ok");
    assert.equal(result.speakerCount, 2);

    const turns = truthOf("two-speaker");
    const perTurn = speakerPerTurn(turns, result.intervals);
    const idOf = { A: perTurn[0], B: perTurn[1] };
    assert.notEqual(idOf.A, idOf.B, "the two voices must get different ids");
    turns.forEach((turn, i) => assert.equal(perTurn[i], idOf[turn.speaker], `turn ${i + 1} ("${turn.text}") speaker`));
  });

  test("the original speaker keeps the same id after the other one talks (A -> B -> A)", async (t) => {
    const env = await realEnv();
    if (!env.installed) return t.skip("diarization not installed");
    const result = await diarizeWav(fixtureSynthetic("two-speaker.wav"), env.config, { timeoutMs: 60_000 });
    const perTurn = speakerPerTurn(truthOf("two-speaker"), result.intervals);
    assert.equal(perTurn[0], perTurn[2]);
    assert.equal(perTurn[2], perTurn[4]);
    assert.equal(perTurn[4], perTurn[6]);
    assert.equal(perTurn[1], perTurn[3]);
  });

  test("a single-speaker recording yields one speaker", async (t) => {
    const env = await realEnv();
    if (!env.installed) return t.skip("diarization not installed");
    const result = await diarizeWav(fixtureSynthetic("single-speaker.wav"), env.config, { timeoutMs: 60_000 });
    assert.equal(result.status, "ok");
    assert.equal(result.speakerCount, 1);
  });

  test("overlapping speech: two speakers found and most turns right (a short overlapped reply may be wrong)", async (t) => {
    const env = await realEnv();
    if (!env.installed) return t.skip("diarization not installed");
    const result = await diarizeWav(fixtureSynthetic("overlap.wav"), env.config, { timeoutMs: 60_000 });
    assert.equal(result.speakerCount, 2);
    const turns = truthOf("overlap");
    const perTurn = speakerPerTurn(turns, result.intervals);
    const idOf = { A: perTurn[0], B: perTurn[1] };
    const correct = turns.filter((turn, i) => perTurn[i] === idOf[turn.speaker]).length;
    t.diagnostic(`overlap: ${correct}/${turns.length} turns correct`);
    assert.ok(correct >= 6, `only ${correct}/${turns.length} turns correct`);
  });

  test("silent audio produces no speakers", async (t) => {
    const env = await realEnv();
    if (!env.installed) return t.skip("diarization not installed");
    const silent = path.join(env.root, "silent.wav");
    makeSilentWav(silent, 4);
    const result = await diarizeWav(silent, env.config, { timeoutMs: 60_000 });
    assert.equal(result.status, "ok");
    assert.deepEqual(result.intervals, []);
  });

  test("a missing model is reported as unavailable, never as a normal result", async (t) => {
    const env = await realEnv();
    if (!env.installed) return t.skip("diarization not installed");
    // A copy of the script in a directory that has no models next to it.
    const lonely = path.join(env.root, "lonely");
    mkdirSync(lonely);
    copyFileSync(env.config.diarizationScript, path.join(lonely, "diarize.py"));
    const result = await diarizeWav(fixtureSynthetic("two-speaker.wav"), { ...env.config, diarizationScript: path.join(lonely, "diarize.py") }, { timeoutMs: 30_000 });
    assert.equal(result.status, "unavailable");
    assert.deepEqual(result.intervals, []);
  });

  test("the module refuses audio that is not 16 kHz mono PCM16 (structured error, not a crash)", async (t) => {
    const env = await realEnv();
    if (!env.installed) return t.skip("diarization not installed");
    const stereo = path.join(env.root, "stereo.wav");
    spawnSync("ffmpeg", ["-y", "-v", "error", "-i", fixtureSynthetic("two-speaker.wav"), "-ac", "2", stereo]);
    const result = await diarizeWav(stereo, env.config, { timeoutMs: 30_000 });
    assert.equal(result.status, "failed");
  });
});

describe("real end-to-end: authenticated speaker-aware transcription of a synthetic consultation", () => {
  async function app() {
    const env = await realEnv();
    const keys = await makeAuth();
    env.config.supabaseUrl = TEST_SUPABASE_URL;
    const server = await startServer(env.config, { jwks: keys.jwks });
    cleanups.push(server.close);
    const token = await keys.sign("doctor-real");
    const post = async (name, fields = {}) => {
      const form = new FormData();
      form.append("audio", new Blob([await readFixture(fixtureSynthetic(`${name}.wav`))], { type: "audio/wav" }), `${name}.wav`);
      for (const [key, value] of Object.entries(fields)) form.append(key, value);
      const started = Date.now();
      const res = await fetch(`${server.baseUrl}/api/transcriptions`, { method: "POST", headers: { Authorization: `Bearer ${token}` }, body: form });
      return { res, body: await res.json(), ms: Date.now() - started };
    };
    const patch = async (url, body) =>
      (await fetch(`${server.baseUrl}${url}`, { method: "PATCH", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify(body) })).json();
    const get = async (id) => (await fetch(`${server.baseUrl}/api/transcriptions/${id}`, { headers: { Authorization: `Bearer ${token}` } })).json();
    return { ...env, ...server, post, patch, get };
  }

  test("a two-person conversation becomes speaker-separated, aligned, persisted segments", async (t) => {
    const env = await app();
    if (!env.installed || !env.whisperReady) return t.skip("whisper.cpp or diarization not installed");

    const { res, body, ms } = await env.post("two-speaker");
    t.diagnostic(`full consultation pipeline: ${ms} ms for 17 s of audio`);
    assert.equal(res.status, 201);
    assert.equal(body.reviewStatus, "needs_review");
    assert.deepEqual(body.diarization, { status: "ok", speakerCount: 2 });
    assert.equal(body.speakers.length, 2);
    assert.ok(body.speakers.every((s) => s.role === "unassigned"));

    // Timestamps are ordered and valid.
    for (let i = 0; i < body.segments.length; i++) {
      const segment = body.segments[i];
      assert.ok(segment.endMs > segment.startMs, `segment ${i + 1} has a valid range`);
      if (i > 0) assert.ok(segment.startMs >= body.segments[i - 1].endMs, `segment ${i + 1} is in order`);
    }

    // Compare against ground truth: which segment covers each true turn, and who is it?
    const turns = truthOf("two-speaker");
    const speakerFor = (turn) => {
      const mid = (turn.startMs + turn.endMs) / 2;
      return body.segments.find((s) => mid >= s.startMs - 200 && mid <= s.endMs + 200);
    };
    const first = { A: speakerFor(turns[0]).speakerId, B: speakerFor(turns[1]).speakerId };
    assert.ok(first.A && first.B && first.A !== first.B);
    turns.forEach((turn, i) => {
      const segment = speakerFor(turn);
      assert.ok(segment, `a segment exists for turn ${i + 1}`);
      assert.equal(segment.speakerId, first[turn.speaker], `turn ${i + 1} ("${turn.text}") has the right speaker`);
    });
    assert.match(body.text, /headache/i);
    assert.match(speakerFor(turns[1]).text, /headache/i, "text and speaker are aligned to the same segment");
    assert.deepEqual(await leftoverFiles(env.tmpDir), []);

    // The doctor maps a role to a speaker; it persists and applies to that speaker's segments.
    const doctorId = first.A;
    const mapped = await env.patch(`/api/transcriptions/${body.id}/speakers`, { speakerId: doctorId, role: "doctor" });
    assert.equal(mapped.speakers.find((s) => s.id === doctorId).role, "doctor");
    const reread = await env.get(body.id);
    assert.equal(reread.speakers.find((s) => s.id === doctorId).role, "doctor");
    assert.deepEqual(reread.segments, body.segments);
    assert.equal(reread.reviewStatus, "needs_review");
  });

  test("a single-speaker recording yields exactly one speaker", async (t) => {
    const env = await app();
    if (!env.installed || !env.whisperReady) return t.skip("whisper.cpp or diarization not installed");
    const { res, body } = await env.post("single-speaker");
    assert.equal(res.status, 201);
    assert.equal(body.speakers.length, 1);
    assert.ok(body.segments.every((s) => s.speakerId === "speaker_1"));
  });

  test("expectedSpeakers is honored by the real diarizer (forcing 1 speaker merges two voices)", async (t) => {
    const env = await app();
    if (!env.installed || !env.whisperReady) return t.skip("whisper.cpp or diarization not installed");
    const forcedOne = await env.post("two-speaker", { expectedSpeakers: "1" });
    assert.equal(forcedOne.res.status, 201);
    assert.equal(forcedOne.body.speakers.length, 1);
    const forcedTwo = await env.post("two-speaker", { expectedSpeakers: "2" });
    assert.equal(forcedTwo.body.speakers.length, 2);
  });

  test("the legacy /api/transcribe still returns the v1 shape with real whisper.cpp", async (t) => {
    const env = await app();
    if (!env.whisperReady) return t.skip("whisper.cpp not installed");
    const res = await postAudio(env.baseUrl, await readFixture(fixtureSynthetic("two-speaker.wav")));
    assert.equal(res.status, 200);
    const body = await res.json();
    assert.deepEqual(Object.keys(body).sort(), ["durationSeconds", "text"]);
    assert.match(body.text, /headache/i);
  });
});
